name: Build and push image

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the all branches
  push:
    branches: [ '**' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Extract branch name
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF##*/})"
        id: extract_branch

      # Login to docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build and push latest image - if master branch
      - name: Build and push latest image
        if: ${{ steps.extract_branch.outputs.branch == 'master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wpjsro/build-base:latest

      # Build and push image with tag by branch name - if not master branch
      - name: Build and push tagged image
        if: ${{ steps.extract_branch.outputs.branch != 'master' }}
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wpjsro/build-base:${{ steps.extract_branch.outputs.branch }}